### PR TITLE
Update code to use `Faculty` attribute

### LINKED ISSUE #12: As a forgetful user, I can store a professor's faculty
... so that I can see the faculty that a professor belongs to

### LINKED ISSUE #51: Update code to use the Faculty attribute
Command includes:
- [ ] Add
- [ ] Edit

### PR DESCRIPTION
**Pull request by JerryWang0000**
The attribute is now restricted to typing in exactly the same string as the name of the faculty.

Closes #51

### CODE REVIEW

**Comment by JerryWang0000** [comment]
Merge Faculty First then reopen the PR

**Comment by Pluiexo** [comment]
> Merge Faculty First then reopen the PR

You can reopen this PR if you want, since the faculty has been merged

**Comment by JerryWang0000** [comment]
Need to change some codes cause now the value stored in `Faculty` is Enum

**Review by whitesnowx — APPROVED** [review]
LGTM 👍

**Pull request merged**
